FROM ruby:3.4.3

# 必要なパッケージをインストール
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

# 作業ディレクトリを設定
WORKDIR /backend

# Gemfileを先にコピーしてインストール
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Entrypointスクリプトのコピー＆実行権限付与
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

# ポート開放
EXPOSE 8080

# Railsサーバを起動
CMD ["rails", "server", "-b", "0.0.0.0", "-p", "8080"]
