services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: nextblogapp-image
    container_name: nextblogapp-container
    volumes:
      - .:/backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:17.4
    container_name: nextblogapp-db
    volumes:
      - nextblogapp-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kensuke
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nextblogapp_development

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z # だいたいでOK
    container_name: nextblogapp-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniosecret
    ports:
      - "9000:9000" # S3互換エンドポイント
      - "9001:9001" # コンソールUI
    volumes:
      - nextblogapp-minio-data:/data

volumes:
  nextblogapp-db-data:
  nextblogapp-minio-data:
